spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/rai
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update-create
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8088
